
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE TAREFAS DROP CONSTRAINT FK_TAREFAS_USUARIOS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TAREFAS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USUARIOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE USUARIOS_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE TAREFAS_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE USUARIOS (
    ID_USUARIO NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL
);
/

CREATE TABLE TAREFAS (
    ID_TAREFA_

