BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE LABDATABASE.TAREFAS DROP CONSTRAINT FK_TAREFAS_USUARIOS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
  
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE LABDATABASE.TAREFAS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE LABDATABASE.USUARIOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE LABDATABASE.USUARIOS_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE LABDATABASE.TAREFAS_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/


CREATE TABLE LABDATABASE.USUARIOS (
    ID_USUARIO NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL
);
/

CREATE TABLE LABDATABASE.TAREFAS (
    ID_TAREFA NUMBER PRIMARY KEY,
    TITULO VARCHAR2(100) NOT NULL,
    DESCRICAO VARCHAR2(500),
    DATA_CRIACAO DATE DEFAULT SYSDATE NOT NULL,
    DATA_LIMITE DATE,
    STATUS VARCHAR2(20) DEFAULT 'Pendente',
    ID_USUARIO NUMBER NOT NULL,
    CONSTRAINT FK_TAREFAS_USUARIOS FOREIGN KEY (ID_USUARIO)
        REFERENCES LABDATABASE.USUARIOS (ID_USUARIO)
);
/


CREATE SEQUENCE LABDATABASE.USUARIOS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/
CREATE SEQUENCE LABDATABASE.TAREFAS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/


CREATE OR REPLACE TRIGGER LABDATABASE.TRG_USUARIOS_ID
BEFORE INSERT ON LABDATABASE.USUARIOS
FOR EACH ROW
BEGIN
  IF :NEW.ID_USUARIO IS NULL THEN
    SELECT LABDATABASE.USUARIOS_SEQ.NEXTVAL INTO :NEW.ID_USUARIO FROM DUAL;
  END IF;
END;
/
SHOW ERRORS;
/

CREATE OR REPLACE TRIGGER LABDATABASE.TRG_TAREFAS_ID
BEFORE INSERT ON LABDATABASE.TAREFAS
FOR EACH ROW
BEGIN
  IF :NEW.ID_TAREFA IS NULL THEN
    SELECT LABDATABASE.TAREFAS_SEQ.NEXTVAL INTO :NEW.ID_TAREFA FROM DUAL;
  END IF;
END;
/
SHOW ERRORS;
/


INSERT INTO LABDATABASE.USUARIOS (NOME, EMAIL) VALUES ('Renan Miguel','renan@email.com');
/
INSERT INTO LABDATABASE.USUARIOS (NOME, EMAIL) VALUES ('João Silva','joao@email.com');
/

INSERT INTO LABDATABASE.TAREFAS (TITULO, DESCRICAO, DATA_LIMITE, STATUS, ID_USUARIO)
VALUES ('Estudar Oracle','Aprender comandos SQL', TO_DATE('2025-10-16','YYYY-MM-DD'),'Pendente',1);
/
INSERT INTO LABDATABASE.TAREFAS (TITULO, DESCRICAO, DATA_LIMITE, STATUS, ID_USUARIO)
VALUES ('Fazer trabalho da faculdade','Implementar CRUD', TO_DATE('2025-10-21','YYYY-MM-DD'),'Em andamento',1);
/
INSERT INTO LABDATABASE.TAREFAS (TITULO, DESCRICAO, DATA_LIMITE, STATUS, ID_USUARIO)
VALUES ('Enviar relatório','Relatório semanal', TO_DATE('2025-10-12','YYYY-MM-DD'),'Concluída',2);
/

COMMIT;
/
